### ISSUE TITLE
Unable to Fully Build `sfpi-binutils`

### ISSUE THREAD

**Issue by ThePerfectComputer** [tenstorrent/sfpi-binutils#1]
I'm trying to package up gcc(with support for TT intrinsics and custom instructions) in a format acceptable to mainline distro package managers. I'm getting stuck building `sfpi-binutils` as gcc complains `"Must define one of IN_ASSEMBLER or IN_DISASSEMBLER"`.

It seems certain files that include `include/opcode/riscv.h` will define `IN_ASSEMBLER` or `IN_DISASSEMBLER `, but for the gcc-10.2.0 binutils target, `gdb/riscv-tdep.c` is not one of those files. Likewise, for gcc-12.2.0, `sim/riscv/sim-main.c` includes `riscv.h` but defines neither `IN_ASSEMBLER` nor `IN_DISASSEMBLER`.

You can see the build flags I've been using [here](https://github.com/ThePerfectComputer/tt-gcc/blob/gcc_10.2.0/tt-gcc.nix#L53-L75).

**Comment by ThePerfectComputer** [comment]
The build flags I linked to above were obtained by running `./riscv32-unknown-elf-gcc -v` in a Ubuntu docker container into which I cloned the `sfpi-rel` binaries.

**Comment by mbahnasTT** [comment]
Some context:
It seems the sfpi-toolchain installs pre-built binaries for TT's GCC port(the one that adds wormhole and grayskull as -m<arch> target) instead of building from source. This isn't necessarily an issue, but for various reasons, we may need to build SFPI from source… And I think the upstream sfpi-binutils may be missing some files to fully enable this…

**Comment by ThePerfectComputer** [comment]
I was actually able to fix this - will upload patch later

**Comment by pgkeller** [comment]
fyi @nathan-TT

**Comment by nathan-TT** [comment]
aha, they reached out to my personal email too :)

**Comment by ThePerfectComputer** [comment]
The [following changes](https://github.com/ThePerfectComputer/sfpi-binutils/commit/ef96897f5209541d2c6b3464e40430d5cb02b1f6) allow `sfpi-binutils` to build to completion. Judging by the contents of [sfpi-rel](https://github.com/tenstorrent/sfpi-rel/tree/master/compiler), it seems that TensTorrent is building sfpi against newlib? Is this correct?

Anyways, after several hours of poking at it, I've been unable to complete a gcc stage 2 bare metal elf build that has support for newlib...

Does TensTorrent have any internal scripts they use to build sfpi? I poked around on GitHub for any GitHub Ci action scripts producing sfpi artifacts, but it seems that TensTorrent has been uploading sfpi gcc x86 binaries targeting Ubuntu directly as releases. This is really not a good long term solution - mainly because other architectures exist such as POWER9 machines. Furthermore, in certain environments, using Ubuntu is not an option - i.e. RedHat - etc.

Certainly not requesting TT to build for every arch/distro combo, but releasing build scripts would make a great starting point for others who wish to bring TT tools to the distro and arch of their choosing.

**Comment by ThePerfectComputer** [comment]
One can find the script I've been using to build `sfpi` [here](https://github.com/ThePerfectComputer/tt-gcc/blob/gcc_10.2.0/tt-gcc.nix)

**Comment by ThePerfectComputer** [comment]
I think at one point I had tried `https://github.com/tenstorrent/sfpi-tt-gcc`, but I'm not sure it builds well outside Ubuntu.

**Comment by nathan-TT** [comment]
1) clone the tt-gcc component `git clone -b tt-rel/gcc-12.2 https://github.com/tenstorrent/tt-gcc.git` (or `git@github.com:tenstorrent/tt-gcc.git` of course)
2) recursively update its submodules `git -C tt-gcc submodule update --recursive --init`
3) create & enter build dir `mkdir build ; cd build`
4) configure `../tt-gcc/configure --prefix=$SOMEWHERE -disable-multilib -with-abi=ilp32 -with-arch=rv32i`
5) build `make -j$NUM`

Hope that helps. Making this process easier is on our roadmap.

**Comment by ThePerfectComputer** [comment]
Is `https://github.com/tenstorrent/tt-gcc.git` public facing?

I tried the above commands with `https://github.com/tenstorrent/sfpi-tt-gcc/tree/c0ed5d7f6f9d7aa24d848a0dc792cc32ca1c9215`, but hit bugs until I patched binutils manually with `https://github.com/ThePerfectComputer/sfpi-binutils/commit/ef96897f5209541d2c6b3464e40430d5cb02b1f6`.

I'm almost positive that `sfpi-tt-gcc` as is will not build locally without being patched. If you've had any success building `sfpi-tt-gcc` can you share your exact environment you used to build? The more details the better including info such as ubuntu distro, compiler, kernel, etc.

**Comment by ThePerfectComputer** [comment]
At this point, I'm happy to start with any path that will allow me to build a working tt-gcc from source. I've spent well over 20 hours trying the methods suggested in the docs(although in Nix not in Ubuntu).

I know the binaries released for Ubuntu work as I've tried them - but I do really need a path to build from source.

The [script I've been using](https://github.com/ThePerfectComputer/tt-gcc/blob/gcc_10.2.0/tt-gcc.nix) which I wrote myself does build a working gcc with support for gray skull and WH intrinsics. The gcc stage 2 however suffers from being unable to locate where it the `as` binutils is located - I'm not sure why and current investigations have been unfruitful.

**Comment by mbahnasTT** [comment]
Thanks @ThePerfectComputer for sharing your development results.
@nathan-TT, I appreciate your help, please

**Comment by nathan-TT** [comment]
> Is `https://github.com/tenstorrent/tt-gcc.git` public facing?

Apologies, it is indeed sfpi-tt-gcc. Builds with the commands I mention on a Ubuntu 20.04.6 LTS machine.

**Comment by ThePerfectComputer** [comment]
Ok. Just tried building `sfpi-tt-gcc` in docker Ubuntu:20.04 according to the official instructions which failed(as expected) due to the bug I mentioned earlier and patched [here](https://github.com/ThePerfectComputer/sfpi-binutils/commit/ef96897f5209541d2c6b3464e40430d5cb02b1f6).

@nathan-TT , have you tried building `sfpi-tt-gcc` in a clean docker container recently from source? As you can see, `sfpi-tt-gcc` will not build whether in Ubuntu 20.04 or Nix without the patches I mentioned above. 

Furthermore, you can see that on my repo I linked to earlier, I have a minimal script which will build a functional `binutils(with TT intrinsics) -> gcc1 -> NewlibC -> gcc2` in about 5 minutes. The only issue with that build is the gcc2 that gets built cannot find the `as` output from the binutils stage. To get around this, I have gcc2 emit `*.s` files which I then pass to `as` - obviously not optimal... Again, trying to figure out what that happens - but not yet fruitful.

The path forward I think makes most sense is trying to tweak my script so that gcc2 can resolve binutil paths correctly. The `sfpi-tt-gcc` build process TT documentation references fetches about 6 GB worth of sources and takes a very long time to build - which I'd say is notably inferior to my 5 minute script - should I be able to correct the path resolution issue.

```bash
docker run -it ubuntu:20.04
mkdir srcs
cd srcs
apt update
apt-get install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev git
git clone --recursive https://github.com/tenstorrent/sfpi-tt-gcc.git -b tt-rel/riscv-gcc-10.2.0
cd sfpi-tt-gcc/
mkdir build
cd build
../configure --prefix=$SOMEWHERE -disable-multilib -with-abi=ilp32 -with-arch=rv32i
make -j`nproc`
<redacted>
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[6]: *** [Makefile:386: lib_a-sysclose.o] Error 1
make[6]: *** Waiting for unfinished jobs....
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[6]: *** [Makefile:386: lib_a-sysclose.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[6]: *** [Makefile:392: lib_a-sysfcntl.o] Error 1
make[6]: *** [Makefile:398: lib_a-sysfstat.o] Error 1
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[6]: *** [Makefile:410: lib_a-sysgettod.o] Error 1
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[6]: *** [Makefile:398: lib_a-sysfstat.o] Error 1
riscv32-unknown-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[6]: *** [Makefile:404: lib_a-sysgetpid.o] Error 1
make[6]: Leaving directory '/srcs/sfpi-tt-gcc/build/build-newlib-nano/riscv32-unknown-elf/newlib/libc/syscalls'
Making all in ssp
riscv32-unknown-elf-gcc: fatal er
```

**Comment by ThePerfectComputer** [comment]
actually - excuse me - wrong prefix - just caught that - will retry

**Comment by ThePerfectComputer** [comment]
ok - got it working. It's on me to make this work in nix then...

**Comment by ThePerfectComputer** [comment]
Getting it building in Nix is not forthcoming. I give up. Will use Ubuntu docker for now. Please consider simplifying the build script for the future to help with making it portable to other distros if possible.

**Comment by ThePerfectComputer** [comment]
I did manage to get a TT's compiler ported to nix it seems, although now, whenever I compile,I get the following warning:

`/nix/store/n70bcc92l5pzs52vlv13ljcj3abp01ri-riscv32-none-elf-binutils-2.39/bin/riscv32-none-elf-ld: /nix/store/ryn5n2jhnplg97maxyc5sa7nvi7cdb3q-newlib-riscv32-none-elf-4.1.0/riscv32-none-elf/lib/libc.a(lib_a-__call_atexit.o): unsupported relocation type 0x3d`

I'm wondering if this is anything to be concerned about.
